[general]
bars = 80
framerate = 60

[input]
method = pulse
source = auto

[smoothing]
noise_reduction = 30

[output]
method = raw
channels = stereo
raw_target = /dev/stdout
data_format = ascii
ascii_max_range = 100
bar_delimiter = 59
frame_delimiter = 10
